name: Mise a jour Dossier de Vol

on:
  schedule:
    - cron: '0,5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Installation Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installation Outils
        run: |
          pip install requests selenium webdriver-manager Pillow python-docx

      # --- 1. TELECHARGEMENT IMAGES ---
      - name: Script FRONTS
        env:
          METEO_LOGIN: ${{ secrets.METEO_LOGIN }}
          METEO_PASS: ${{ secrets.METEO_PASS }}
        run: python main.py

      - name: Script TEMSI
        env:
          METEO_LOGIN: ${{ secrets.METEO_LOGIN }}
          METEO_PASS: ${{ secrets.METEO_PASS }}
        run: python temsi_france.py

      - name: Script WINTEM
        env:
          METEO_LOGIN: ${{ secrets.METEO_LOGIN }}
          METEO_PASS: ${{ secrets.METEO_PASS }}
        run: python wintem_france.py

      - name: Script SIGMET
        env:
          METEO_LOGIN: ${{ secrets.METEO_LOGIN }}
          METEO_PASS: ${{ secrets.METEO_PASS }}
        run: python sigmet_france.py

      # --- 2. GENERATION DU DOCUMENT ---
      - name: Création du Word
        run: python create_briefing.py

      # --- 3. SAUVEGARDE ---
      - name: Git Push
        run: |
          git config --global user.name 'Robot Meteo'
          git config --global user.email 'robot@meteo.fr'
          git add *.png Dossier_Vol_Complet.docx
          git commit -m "Mise a jour Dossier Vol" || echo "Rien a changer"
          git push
