name: Mise a jour Carte Aero

on:
  schedule:
    - cron: '0,5 * * * *'  # H+00 et H+05
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Installation Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installation Outils
        run: |
          pip install requests selenium webdriver-manager Pillow

      # 1. FRONTS
      - name: Script FRONTS
        env:
          METEO_LOGIN: ${{ secrets.METEO_LOGIN }}
          METEO_PASS: ${{ secrets.METEO_PASS }}
        run: python main.py

      # 2. TEMSI
      - name: Script TEMSI
        env:
          METEO_LOGIN: ${{ secrets.METEO_LOGIN }}
          METEO_PASS: ${{ secrets.METEO_PASS }}
        run: python temsi_france.py

      # 3. WINTEM
      - name: Script WINTEM
        env:
          METEO_LOGIN: ${{ secrets.METEO_LOGIN }}
          METEO_PASS: ${{ secrets.METEO_PASS }}
        run: python wintem_france.py

      # 4. SIGMET
      - name: Script SIGMET
        env:
          METEO_LOGIN: ${{ secrets.METEO_LOGIN }}
          METEO_PASS: ${{ secrets.METEO_PASS }}
        run: python sigmet_france.py

      # 5. SAUVEGARDE
      - name: Git Push
        run: |
          git config --global user.name 'Robot Meteo'
          git config --global user.email 'robot@meteo.fr'
          git add *.png
          git commit -m "Update Cartes + SIGMET" || echo "Rien a changer"
          git push
