- name: Lancement Script FRONTS (Original)
        env:
          METEO_LOGIN: ${{ secrets.METEO_LOGIN }}
          METEO_PASS: ${{ secrets.METEO_PASS }}
        run: python main.py

      - name: Lancement Script TEMSI (Nouveau)
        env:
          METEO_LOGIN: ${{ secrets.METEO_LOGIN }}
          METEO_PASS: ${{ secrets.METEO_PASS }}
        run: python temsi_france.py

      - name: Enregistrement de TOUTES les images
        run: |
          git config --global user.name 'Robot Meteo'
          git config --global user.email 'robot@meteo.fr'
          git add *.png
          git commit -m "Mise a jour Cartes Meteo" || echo "Pas de changement"
          git push
