name: Mise a jour Dossier de Vol

on:
  schedule:
    - cron: '0,5 * * * *'  # H+00 et H+05
  workflow_dispatch:      # Bouton manuel

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Installation Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installation Outils
        run: |
          # On ajoute 'python-docx' pour générer le Word
          pip install requests selenium webdriver-manager Pillow python-docx

      # --- BLOC METEO (Récupération des images) ---
      - name: Script FRONTS
        env:
          METEO_LOGIN: ${{ secrets.METEO_LOGIN }}
          METEO_PASS: ${{ secrets.METEO_PASS }}
        run: python main.py

      - name: Script TEMSI
        env:
          METEO_LOGIN: ${{ secrets.METEO_LOGIN }}
          METEO_PASS: ${{ secrets.METEO_PASS }}
        run: python temsi_france.py

      - name: Script WINTEM
        env:
          METEO_LOGIN: ${{ secrets.METEO_LOGIN }}
          METEO_PASS: ${{ secrets.METEO_PASS }}
        run: python wintem_france.py

      - name: Script SIGMET
        env:
          METEO_LOGIN: ${{ secrets.METEO_LOGIN }}
          METEO_PASS: ${{ secrets.METEO_PASS }}
        run: python sigmet_france.py

      # --- BLOC DOCUMENT (Assemblage du Word) ---
      - name: Génération Dossier Word
        run: python create_briefing.py

      # --- SAUVEGARDE FINALE ---
      - name: Git Push
        run: |
          git config --global user.name 'Robot Meteo'
          git config --global user.email 'robot@meteo.fr'
          # On ajoute les images PNG et le fichier DOCX
          git add *.png *.docx
          git commit -m "Mise a jour Dossier Vol Complet" || echo "Rien a changer"
          git push
