name: Mise a jour Carte Aero

on:
  schedule:
    - cron: '0 * * * *'  # Toutes les heures
  workflow_dispatch:      # Manuel

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Installation Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installation Outils
        run: |
          pip install requests selenium webdriver-manager

      # 1. SCRIPT FRONTS (Votre script fonctionnel WAFC)
      - name: Lancement Script FRONTS
        env:
          METEO_LOGIN: ${{ secrets.METEO_LOGIN }}
          METEO_PASS: ${{ secrets.METEO_PASS }}
        run: python main.py

      # 2. SCRIPT TEMSI (Le nouveau script corrigé)
      - name: Lancement Script TEMSI
        env:
          METEO_LOGIN: ${{ secrets.METEO_LOGIN }}
          METEO_PASS: ${{ secrets.METEO_PASS }}
        run: python temsi_france.py

      # 3. SAUVEGARDE
      - name: Git Push
        run: |
          git config --global user.name 'Robot Meteo'
          git config --global user.email 'robot@meteo.fr'
          git add *.png
          git commit -m "Mise a jour Cartes" || echo "Rien a changer"
          git push
