name: Mise a jour Carte Aero

on:
  schedule:
    # La virgule permet de définir plusieurs minutes : 00 et 05
    - cron: '0,5 * * * *'
  workflow_dispatch:      # Permet le lancement manuel

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Installation Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installation Outils
        run: |
          pip install requests selenium webdriver-manager

      # 1. SCRIPT FRONTS (WAFC)
      - name: Lancement Script FRONTS
        env:
          METEO_LOGIN: ${{ secrets.METEO_LOGIN }}
          METEO_PASS: ${{ secrets.METEO_PASS }}
        run: python main.py

      # 2. SCRIPT TEMSI (France)
      - name: Lancement Script TEMSI
        env:
          METEO_LOGIN: ${{ secrets.METEO_LOGIN }}
          METEO_PASS: ${{ secrets.METEO_PASS }}
        run: python temsi_france.py

      # 3. SAUVEGARDE
      - name: Git Push
        run: |
          git config --global user.name 'Robot Meteo'
          git config --global user.email 'robot@meteo.fr'
          git add *.png
          git commit -m "Mise a jour Cartes (H+00 / H+05)" || echo "Rien a changer"
          git push
