name: Mise a jour Carte Aero

on:
  schedule:
    - cron: '0,5 * * * *'  # H+00 et H+05
  workflow_dispatch:      # Manuel

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Installation Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installation Outils
        run: |
          pip install requests selenium webdriver-manager

      # 1. CARTE FRONTS
      - name: Script FRONTS (WAFC)
        env:
          METEO_LOGIN: ${{ secrets.METEO_LOGIN }}
          METEO_PASS: ${{ secrets.METEO_PASS }}
        run: python main.py

      # 2. CARTE TEMSI FRANCE
      - name: Script TEMSI FRANCE
        env:
          METEO_LOGIN: ${{ secrets.METEO_LOGIN }}
          METEO_PASS: ${{ secrets.METEO_PASS }}
        run: python temsi_france.py

      # 3. CARTE WINTEM FRANCE (20/100)
      - name: Script WINTEM FRANCE
        env:
          METEO_LOGIN: ${{ secrets.METEO_LOGIN }}
          METEO_PASS: ${{ secrets.METEO_PASS }}
        run: python wintem_france.py

      # 4. SAUVEGARDE
      - name: Git Push
        run: |
          git config --global user.name 'Robot Meteo'
          git config --global user.email 'robot@meteo.fr'
          git add *.png
          git commit -m "Update Cartes (H+00 / H+05)" || echo "Rien a changer"
          git push
